config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "lists#index"

  resources :lists do
    resources :bookmarks, only: [ :new, :create, :edit, :update ]
  end
  resources :bookmarks, only: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :comment, length: { minimum: 6 }, presence: true
  validates :movie_id, uniqueness: { scope: :list_id }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks, dependent: :destroy

  validates :name, presence: true, uniqueness: true
  validates :description, presence: true, length: { minimum: 6 }
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks

  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :avatar
  has_many :lists, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:avatar])
    devise_parameter_sanitizer.permit(:account_update, keys: [:avatar])
  end
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_bookmark, only: [:destroy, :edit, :update]
  before_action :set_list, only: [:new, :create, :edit, :update]

  def new
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    if @bookmark.save
      redirect_to @list, notice: 'Bookmark was successfully added.'
    else
      flash.now[:alert] = 'Failed to add bookmark. Please ensure a movie is selected and comment is provided.'
      render "lists/show", status: :unprocessable_entity
    end
  end

  def edit
    @bookmark = Bookmark.find(params[:id])
  end

  def update
    @bookmark = Bookmark.find(params[:id])
    if @bookmark.update(bookmark_params)
      redirect_to @list, notice: 'Bookmark was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @bookmark.destroy
    redirect_to bookmark_path, status: :see_other
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end

  def set_bookmark
    @bookmark = Bookmark.find(params[:id])
    unless @bookmark
      flash[:alert] = "Bookmark not found."
      redirect_to bookmarks_path
    end
  end

  def set_list
    @list = List.find(params[:list_id])
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show, :destroy]

  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to lists_path
    else
      render :new
    end
  end

  def edit
    @list = List.find(params[:id])
  end

  def update
    @list = List.find(params[:id])
    if @list.update(list_params)
      redirect_to lists_path
    else
      render :edit
    end
  end

  def destroy
    @list.destroy
    redirect_to lists_path, status: :see_other
  end

  private

  def list_params
    params.require(:list).permit(:name, :description, :image)
  end

  def set_list
    @list = List.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/edit.html.erb
<div class="container-index">

  <h2>Edit your comment !</h2>

  <%= simple_form_for [@list, @bookmark] do |f| %>
    <% if @bookmark.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@bookmark.errors.count, "error") %> prohibited this bookmark from being saved:</h2>
        <ul>
          <% @bookmark.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <%= f.input :comment, as: :text, label: 'Comment' %>
    <%= f.button :submit, 'Add Bookmark' %>
    <% end %>
</div>

app/views/bookmarks/new.html.erb
<div class="container-index">

  <h1> Create a bookmark !</h1>

  <%= simple_form_for [@list, @bookmark] do |f| %>
   <% if @bookmark.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bookmark.errors.count, "error") %> prohibited this bookmark from being saved:</h2>
      <ul>
        <% @bookmark.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.input :movie_id, collection: Movie.all, label_method: :title, value_method: :id, prompt: 'Choose a movie', label: 'Movie' %>
  <%= f.input :comment, as: :text, label: 'Comment' %>
  <%= f.button :submit, 'Add Bookmark' %>
  <% end %>


  <%= link_to "Back", list_path(@list), class: "btn btn-secondary" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Watch3r, log your favorite films, comment, enjoy !</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/sweetalert2@11.7.1/dist/sweetalert2.min.css">
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% if user_signed_in? %>
      <%= render "shared/navbar" %>
    <% else %>
      <span></span>
    <% end %>

  <%= yield %>

      <%= render "shared/flashes" %>

    <% if user_signed_in? %>
      <%= render "shared/footer" %>
    <% else %>
      <span></span>
    <% end %>
  </body>

</html>

app/views/lists/edit.html.erb
<div class="container-show">

  <h2 class="text-center">Edit your list !</h2>

  <%= render "shared/form" %>

  <div>
    <%= link_to "Back", list_path(@list), class:"btn btn-secondary my-3" %>
  </div>
</div>

app/views/lists/index.html.erb
<div class="container-index mt-5">

  <div class="header">
    <h1 class="text-center">List of Movies</h1>
  </div>

  <div class= "flexbox">
  <% @lists.each do |list| %>
    <div class="card" style="width: 18rem;">
      <img class="card-img-top" src= <%= list.image %>  alt="Card image cap">
      <div class="card-body">
        <h5 class="card-title"> <%= list.name %></h5>
        <%= link_to "Go to list", list_path(list) %>
      </div>
    </div>
  <% end %>
  </div>

  <div>
    <%= link_to "New List", new_list_path, class: "btn btn-primary" %>
  </div>
</div>

app/views/lists/new.html.erb
<div class="container-index mt-5">
  <div class="title-new-list">
    <h2>Create a new list !</h2>
  </div>

  <%= render "shared/form" %>

  <div class="my-3">
    <%= link_to "Back", lists_path, class: "btn btn-secondary" %>
  </div>
</div>

app/views/lists/show.html.erb
<div class="container-show">
  <div class="title-list">
    <h2 class="text-center"><%= @list.name.humanize %></h2>
  </div>

  <div class="infos-list">
    <div class="list-description">
      <p><strong>Description:</strong>
        <% if @list.description.nil? %>
          No description for this list.
        <% else %>
        <%= @list.description %>
        <% end %></p>
        <p><strong>Number of movies:</strong> <%= @list.movies.count %></p>
    </div>

    <div class="list-links">
      <%= link_to "Edit", edit_list_path(@list), class: "btn btn-primary" %>
      <%= link_to "Delete", list_path(@list), data: {turbo_method: :delete, turbo_confirm: "Are you sure to delete your list : #{@list.name}?"}, class: "btn btn-danger" %>
      <%= link_to "Back", lists_path, class:"btn btn-secondary" %>
    </div>
  </div>

  <div class="movie-list">
    <% if @list.movies.empty? %>
      <p>No movies in this list, add one now !</p>
    <% else %>
          <% @list.movies.each do |movie| %>
          <% bookmark = Bookmark.find_by(list: @list, movie: movie) %>

          <div class="movie-card">
             <%= image_tag movie.poster_url, alt: movie.title, :class=>"movie-poster"  %>

              <div class="movie-info">

                <div class="movie-title">
                  <strong><%= movie.title %> <span class="text-muted font-weight-normal">• <%= movie.rating.round(1) %> <i class="fas fa-star star-yellow"></i></span></strong>
                </div>

                <div class="movie-overview my-2">
                  <small class="text-muted"><%= movie.overview %></small>
                </div>

                <div class="movie-details">
                  <div class="movie-comment">
                      <i class="fas fa-quote-left mr-2"></i><small class="flex-grow-1"> <%= bookmark.comment %> </small><i class="fas fa-quote-right mr-2"></i>
                  </div>

                  <div class="movie-links">
                    <small><%= link_to 'Delete', bookmark_path(bookmark), data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to remove #{movie.title} from your #{@list.name} list"}, class: 'text-danger' %></small>
                    <small> <%= link_to "Edit", edit_list_bookmark_path( @list, bookmark) %></small>
                  </div>

                </div>
            </div>

          </div>

      <% end %>
    <% end %>
  </div>

  <div class="list-buttons">
    <%= link_to "Add a movie", new_list_bookmark_path(@list), class: "btn btn-primary" %>
    <%= link_to "Back", lists_path, class: "btn btn-secondary" %>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer">
  <div class="footer-copyright">
    This footer is made with <i class="fas fa-heart"></i> by Hufer02
  </div>

  <div class="footer-logo">
    <%= link_to image_tag("https://svgsilh.com/svg_v2/1980184.svg"), root_path  %>
  </div>

  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
</footer>

app/views/shared/_form.html.erb
<%= simple_form_for(@list) do |f| %>
  <%= f.input :name, label: "List Name" %>
  <%= f.input :description, label: "Description" %>
  <%= f.input :image, as: :file %>
  <%= f.button :submit, class: "btn btn-primary" %>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
   <div class="footer-logo">
      <%= link_to image_tag("https://svgsilh.com/svg_v2/1980184.svg"), root_path  %>
    </div>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", root_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Create a list", new_list_path, class: "nav-link mx-2" %>
          </li>

          <li class="nav-item dropdown">
            <% if current_user.avatar.attached? %>
              <%= cl_image_tag current_user.avatar.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <% else %>
              <%= image_tag "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?q=80&w=3540&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <% end %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Profile",  edit_user_registration_path, class: "dropdown-item"%>
             <%= link_to "Log out", destroy_user_session_path, class: "dropdown-item", data: {turbo_method: :delete} %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>